//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAndGamesPivot
    {
        public int Id { get; set; }
        public int User_id { get; set; }
        public int Game_id { get; set; }
        public Nullable<int> Team_id { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual User User { get; set; }
    }
}
